trigger: none

resources:
- repo: self

variables:
  imageName: voting-worker-app
  imageTag: '$(Build.BuildId)'
  ecrRepo: 'worker-app'

stages:
- stage: BuildandPush
  displayName: Build and Push
  jobs:
  - job: BuildandPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/worker/Dockerfile'
        tags: |
          $(imageTag)

    - task: ECRPushImage@1
      displayName: Push image
      inputs:
        awsCredentials: 'aws-creds'
        regionName: 'ap-south-1'
        imageSource: 'imagename'
        sourceImageName: '$(imageName)'
        sourceImageTag: '$(imageTag)'
        repositoryName: '$(ecrRepo)'
        pushTag: $(imageTag)